# config/packages/cache.yaml
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                tags: true
                default_lifetime: 31536000  # 1 year
                #adapter: cache.adapter.pdo
                #provider: 'doctrine.dbal.default_connection'
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://localhost'